### ISSUE TITLE
Sign out 500 error

### ISSUE THREAD

**Issue by cherya** [standardnotes/api-gateway#3]
logs:
```{"meta":{"req":{"url":"/auth/sign_out","headers":{"connection":"close","content-length":"0","user-agent":"Go-http-client/1.1","accept":"application/json","authorization":"Bearer 1:06b1b5ce-d20b-4743-913e-750c7308aaab:MlDa0qLv7Z1hracqBmTN3A","content-type":"application/json","accept-encoding":"gzip"},"method":"POST","httpVersion":"1.0","originalUrl":"/auth/sign_out","query":{}},"res":{"statusCode":500},"responseTime":22},"level":"info","message":"HTTP POST /auth/sign_out"}
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "content-type"
    at ServerResponse.setHeader (_http_outgoing.js:561:3)
    at HttpService.<anonymous> (/var/www/dist/src/Service/HttpService.js:108:22)
    at Generator.next (<anonymous>)
    at fulfilled (/var/www/dist/src/Service/HttpService.js:17:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Seems like it happens here:
https://github.com/standardnotes/api-gateway/blob/d32c7165e1f8c353746c65211b785929a3c82f6d/src/Service/HttpService.ts#L97
because auth service response is `204 No Content` and 'content-type' header is not presented

**Comment by karolsojko** [comment]
Should be fixed now. Please open an issue in https://github.com/standardnotes/standalone/ if that still persists
